apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmsdb
  template:
    metadata:
      labels:
        app: lmsdb
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: yourpassword
            - name: POSTGRES_DB
              value: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {} # For testing only — use PVC for production