name: lms-aks-deployment
on: workflow_dispatch

env:
  ACR_LOGIN_SERVER: lmsacr123.azurecr.io

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: send notification to slack 
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            channel: project-1
            text: "LMS production deployment started"

  linting:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  approval:
    needs: notification
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: approval confirmation
        run: echo "Approval given to deploy into production"

  azure-login:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  build:
    needs:
      - azure-login
      - linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend image
        run: |
          cd api
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/api:latest .

      - name: Build Frontend image
        run: |
          cd webapp
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/webapp:latest .

      - name: Push images to ACR
        run: |
          echo ${{ secrets.AZURE_PASSWORD }} | docker login ${{ env.ACR_LOGIN_SERVER }} --username ${{ secrets.AZURE_USERNAME }} --password-stdin
          docker push ${{ env.ACR_LOGIN_SERVER }}/api:latest
          docker push ${{ env.ACR_LOGIN_SERVER }}/webapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set kubectl context to AKS
        run: |
          az aks get-credentials --resource-group  ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER }} --overwrite-existing

      - name: Deploy postgres 
        run: |
          kubectl apply -f k8s/lms-aks-db-deploy.yml
          kubectl apply -f k8s/lms-aks-db-service.yml
          kubectl rollout status deployment/lmsdb --timeout=300s
          
      - name: Deploy Backend to AKS
        run: |
          kubectl apply -f k8s/lms-aks-be-deploy.yml
          kubectl apply -f k8s/lms-aks-be-service.yml
          kubectl rollout status deployment/backend --timeout=300s

      - name: Deploy Frontend to AKS
        run: |
          kubectl apply -f k8s/lms-aks-fe-deploy.yml
          kubectl apply -f k8s/lms-aks-fe-service.yml
          kubectl rollout status deployment/frontend --timeout=300s
          kubectl get svc frontend

  feedback:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: send notification to slack 
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            channel: project-1
            text: "LMS Application Successfully Deployed into Production..."

